name: Set Admin Claim

on:
  workflow_dispatch:
    inputs:
      target_uid:
        description: 'UID user to set admin claim'
        required: true
        default: ''

jobs:
  set-claim:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Write service account JSON to file
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run: |
          if [ -z "$SERVICE_ACCOUNT_JSON" ]; then
            echo "SERVICE_ACCOUNT_JSON secret is missing" >&2
            exit 1
          fi
          echo "$SERVICE_ACCOUNT_JSON" > serviceAccountKey.json
          chmod 600 serviceAccountKey.json

      - name: Install dependencies
        run: |
          npm ci

      - name: Run set-admin-claim script
        env:
          SERVICE_ACCOUNT_PATH: serviceAccountKey.json
          TARGET_UID: ${{ github.event.inputs.target_uid }}
        run: |
          if [ -z "$TARGET_UID" ]; then
            echo "target_uid input is required" >&2
            exit 1
          fi
          node ./set-admin-claim.js "$SERVICE_ACCOUNT_PATH" "$TARGET_UID"

      - name: Cleanup
        run: |
          shred -u serviceAccountKey.json || rm -f serviceAccountKey.json
